### ISSUE TITLE
cmsmap

### ISSUE THREAD

**Issue by cparello** [Manisso/fsociety#106]
Seems like the urllib dependency is not met, this is written in py 2.7 or 3.7?

1.  Traceback (most recent call last):
  File "/root/.fsociety/tools/CMSmap/cmsmap.py", line 4, in <module>
    from cmsmap.main import main
  File "/root/.fsociety/tools/CMSmap/cmsmap/main.py", line 4, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

        A.  pip install urlparse does not fix it

        B.     try:
    from urllib.parse import urlparse
except ImportError:
     from urlparse import urlparse

fixes the error but gives you

2.
Traceback (most recent call last):
  File "/root/.fsociety/tools/CMSmap/cmsmap.py", line 4, in <module>
    from cmsmap.main import main
  File "/root/.fsociety/tools/CMSmap/cmsmap/main.py", line 12, in <module>
    from .lib.bruteforcer import bruter
  File "/root/.fsociety/tools/CMSmap/cmsmap/lib/bruteforcer.py", line 7, in <module>
    from .requester import requester
  File "/root/.fsociety/tools/CMSmap/cmsmap/lib/requester.py", line 86, in <module>
    class NoRedirects(urllib.request.HTTPRedirectHandler):
AttributeError: 'module' object has no attribute 'request'

**Comment by CRO-THEHACKER** [comment]
not fsociety prob, pip podule isnt installed. Google it!
