### ISSUE TITLE
Dorks

### ISSUE THREAD

**Issue by adarshskiller** [Manisso/fsociety#119]
## Checkboxes

- [ ] Updated fsociety
- [ ] Issue does not already exist
- [ ] fsociety issue, not a tool issue

## Expected Result

```bash

```

## Actual Result

```bash

```
When i am trying dorks it is giving the error as like :

Traceback (most recent call last):
  File "/root/.fsociety/tools/doork/doork.py", line 92, in <module>
    main()
  File "/root/.fsociety/tools/doork/doork.py", line 61, in main
    handler = logging.FileHandler(output)
  File "/usr/lib/python2.7/logging/__init__.py", line 920, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 950, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/root/logs/doork-2020-08-24_03:27:33.txt'

what do i need to do ?

**Comment by thehappydinoa** [comment]
Hi, this version is no longer maintained. Please see the updated version [`fsociety-team/fsociety`](https://github.com/fsociety-team/fsociety).
