### ISSUE TITLE
CUPP

### ISSUE THREAD

**Issue by robertjriga** [Manisso/fsociety#41]
Traceback (most recent call last):
  File "/opt/fsociety/tools/cupp/cupp.py", line 50, in <module>
    years = config.get('years', 'years').split(',')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
> ConfigParser.NoSectionError: No section: 'years'

**Comment by CRO-THEHACKER** [comment]
@Manisso

**Comment by thehappydinoa** [comment]
Please report this at https://github.com/Mebus/cupp this appears to be a tool error.
