### ISSUE TITLE
'sslstrip.py

### ISSUE THREAD

**Issue by robertjriga** [Manisso/fsociety#43]
Traceback (most recent call last):
  File "sslstrip/setup.py", line 6, in <module>
    shutil.copyfile("sslstrip.py", "sslstrip/sslstrip")
  File "/usr/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'sslstrip.py'

**Comment by CRO-THEHACKER** [comment]
Must be a relative file path problem. Ill tag @Manisso
