### ISSUE TITLE
CMSMap : File cmsmap.py

### ISSUE THREAD

**Issue by sundowndev** [Manisso/fsociety#52]
## Checkboxes

- [x] Updated fsociety
- [x] Issue does not already exist
- [ ] fsociety issue, not a tool issue

~~~
Traceback (most recent call last):
  File "/var/www/Infosec/fsociety/tools/CMSmap/cmsmap.py", line 2033, in <module>
    scanner.ForceCMSType()
  File "/var/www/Infosec/fsociety/tools/CMSmap/cmsmap.py", line 194, in ForceCMSType
    WPScan(self.url,self.threads).WPrun()
  File "/var/www/Infosec/fsociety/tools/CMSmap/cmsmap.py", line 357, in WPrun
    bruter.WPXMLRPC_brute()
  File "/var/www/Infosec/fsociety/tools/CMSmap/cmsmap.py", line 1274, in WPXMLRPC_brute
    htmltext = opener.open(req).read()
  File "/usr/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: example.fr/xmlrpc.php
~~~

Ubuntu 17.10

**Comment by CRO-THEHACKER** [comment]
See about redownloading CMSmap. the path is: '.../tools/CMSmap'
