### ISSUE TITLE
how can i fix it

### ISSUE THREAD

**Issue by Mikayil** [Manisso/fsociety#59]
[-] No HTTP/HTTPS provided. Assuming HTTP...
Traceback (most recent call last):
  File "/root/.fsociety/tools/CMSmap/cmsmap.py", line 1997, in <module>
    report.status(msg)
  File "/root/.fsociety/tools/CMSmap/cmsmap.py", line 1842, in status
    self.WriteTextFile("[-] " +msg)
  File "/root/.fsociety/tools/CMSmap/cmsmap.py", line 1861, in WriteTextFile
    f = open(self.fn,"w")
IOError: [Errno 2] No such file or directory: 'logs/cmsmap-2018-06-30_09:42:26.txt'

**Comment by CRO-THEHACKER** [comment]
Dose it exist?

Please reopen if not already fixed! :)
