### ISSUE TITLE
main.py issue

### ISSUE THREAD

**Issue by jorditorresb** [Manisso/fsociety#80]
I try execute but no work...

root@kali:~/CMSmap# python cmsmap.py -t https://example.com
Traceback (most recent call last):
  File "cmsmap.py", line 4, in <module>
    from cmsmap.main import main
  File "/root/CMSmap/cmsmap/main.py", line 4, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

**Comment by CRO-THEHACKER** [comment]
Just: sudo -H pip install urlparse
